### PR TITLE
Updated to sbt version 0.13.12

### PR DESCRIPTION
**Pull request by psalchow**
With this PR the 0.13.12 version of sbt is used that fixes the error when running `clean test`. This PR contains also the changes of @lplotni

### CODE REVIEW

**Comment by psalchow** [comment]
Hi @joelrobotham could you please have a look at this PR and merge it if everything is fine?

**Comment by joelrobotham** [comment]
HI @psalchow.  Just to provide a bit of context, we're only actually using this library on a single project here at REA...  so it was perhaps open-sourced by us a tad too early.... 😊 

I've built with your changes and tested it with our project locally and it all looks good to me. 👍 

I'll merge this change in.  I suspect if this project becomes used by a broader group (and we don't increase our internal usage of it) we should look at options around moving ownership of the master fork to someone who has more motivation to keep it up to date!

Cheers,
Joel

**Comment by joelrobotham** [comment]
I might have to ask my colleague @mmollaverdi if he can take a look at how to get a new version of this published somewhere.  (I'm on leave for a few weeks)

**Comment by psalchow** [comment]
Thanks for merging :-)
I guess there won't be too many changes from our side in the next time

**Comment by mmollaverdi** [comment]
OK, I'll have a look on Monday.

**Pull request merged**
